# Generated by Django 3.2.23 on 2024-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='sda', max_length=100),
        ),
    ]
